### ISSUE TITLE
KeyError: 'Enrollment'

### ISSUE THREAD

**Issue by Kamakshi-Raya** [Spidy20/Attendace_management_system#2]
Kamakshis-MacBook-Pro-8:p1 kamakshi$ python3 AMS_Run.py
31.00870159238623
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Enrollment'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "AMS_Run.py", line 359, in Fillattendances
    aa = df.loc[df['Enrollment'] == Id]['Name'.values]
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 2995, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Enrollment'

**Comment by Hojeah2663** [comment]
Anyone to help with this problem?

**Comment by Spidy20** [comment]
Simple, check your CSV file and match the header name. if it would be
different then this error happens.

**Comment by TalhaaaYaqoob** [comment]
> Anyone to help with this problem?

have you solve this issue

**Comment by Spidy20** [comment]
Yes, I can solve remotely for you, but it will be paid, If you want to do
it by yourself then check the CSV file. Something is wrong in that.
